### ISSUE TITLE
Add Web Development Tools as a prerequisites to attempt exercises

### ISSUE THREAD

**Issue by mauroservienti** [Particular/Workshop#197]
Web Development Tools for 4.6.x and 4.7 are required, otherwise the website projects fail to load and run.

**Comment by adamralph** [comment]
@mauroservienti are you referring to the "ASP.NET and web development" workload?

BTW, are you sure that 4.7 is required? It looks like the exercises are currently using 4.6.1, which is included by default.

Incidentally, I noticed that some of the projects are on 4.5.2. We should align them onto 4.6.1.

**Comment by mauroservienti** [comment]
I simply copied feedback I received, unfortunately it’s hard to verify those things without a clean VM

**Comment by mauroservienti** [comment]
Only one thing tools versions is not necessarily aligned with fx versions

**Comment by adamralph** [comment]
Testing on a clean VM now...
