### ISSUE TITLE
Convert all API hosts in exercises from web projects to OWIN self hosted apps

### ISSUE THREAD

**Issue by mauroservienti** [Particular/Workshop#23]
When exercises are run all WebAPI projects will open a new browser window just for the sake of starting up the web server. Depending on the browser configuration and some random browsers behavior users might end up with several browser windows that each time need to be manually closed.
Moving to console apps with OWIN self-hosted will greatly improve the attendee experience.

**Comment by dvdstelt** [comment]
Setting this will do the same! :)

![image](https://cloud.githubusercontent.com/assets/1257410/22439060/889d77e6-e72e-11e6-9b44-86bd59c4c879.png)

**Comment by mauroservienti** [comment]
I tried that with no success 😢

**Comment by tjeerdhans** [comment]
@dvdstelt's solution is the first thing I did for all the API projects. Worked for me.

**Comment by mauroservienti** [comment]
@tjeerdhans thanks for the feedback I'll update I'll the projects settings to make life easier.

**Comment by tjeerdhans** [comment]
Excellent, thanks :-)

**Comment by mauroservienti** [comment]
the issue with `Don't open a web page` setting is that it is not preserved on pull, so whenever the exercises are pulled on a new machine all those settings are reset to their default values, `Current page`.

**Comment by mauroservienti** [comment]
@dvdstelt should we re-evaluate this?

**Comment by mauroservienti** [comment]
removing myself from this one till we make a decision.

**Comment by adamralph** [comment]
The current demo does not open a web page for any of the hosts, so this is only applies to the exercises. Altering the title and description...

**Comment by mauroservienti** [comment]
Once we'll upgrade to NServiceBus on .NET Core I suggest we move all back-ends to .NET Core as well that will immediately withdraw this. Thoughts?

**Comment by dvdstelt** [comment]
Agreed

**Comment by adamralph** [comment]
Agreed
