### ISSUE TITLE
Migrate to .NET Core, 7.2, and NSB.Extensions.Hosting

### ISSUE THREAD

**Issue by jbogard** [Particular/Workshop#323]
About time for an upgrade I think :)

`net461` -> `netcoreapp3.0`
ASP.NET Core 2.x -> ASP.NET Core 3.0
MSMQ -> ??? (RabbitMQ?)

**Comment by jbogard** [comment]
Also, remove Windsor as the container, I don't think it's needed at all any more.
Remove OWIN hosting, use the `ApiController` instead.

**Comment by dvdstelt** [comment]
It's unlikely we will pick up the suggested changes any time soon, if at all. The workshop currently fits our purpose and the suggested changes wouldn't have an impact on the theories we'd like to share with attendees.
Besides that, with the very rare occasional exception, you are the only one left presenting this workshop at conferences.

But you're welcome to submit a PR, though. :-)
I would also suggest moving to LearningTransport, as this requires less set-up from attendees. With the [PlatformSample package](https://docs.particular.net/platform/platform-sample-package), the Particular Service Platform can be used as well.

**Comment by dvdstelt** [comment]
@jbogard I just updated it to Learning Transport. That should make it more easy for people to complete the exercises without having MSMQ installed.

No idea if it now works in Visual Studio for Mac or anything. If I can, I'll have someone try that. It still needs SQL for persisting Entity Framework stuff.

**Comment by jbogard** [comment]
Ah thanks! One less thing to worry about

**Comment by jbogard** [comment]
Just an FYI, I have a version of this that is all on .NET 6:

https://github.com/jbogard/presentations/tree/master/DistributedTracing/Example

**Comment by dvdstelt** [comment]
@jbogard I used what you [created here](https://github.com/Particular/Workshop/issues/323#issuecomment-1035580483) and removed OpenTelemetry stuff. Modified some stuff and then migrated to LiteDb. Just a NuGet package that should work with multiple resources accessing the database, so it doesn't lock up. It also has a LiteDb Studio with which you can have a look at the database. Instructions have been updated as well. Should not be too hard to update your sample with LiteDb as well, if you want.

**Comment by jbogard** [comment]
Nice! Yeah I was adding the OTel stuff specifically for the demo I was doing there. Thanks!
