### ISSUE TITLE
Mention prerequisites such as Windows 10 and Visual Studio Code in Workshop description.

### ISSUE THREAD

**Issue by mpavel** [Particular/Workshop#324]
Hey there, I subscribed to the "SOA Done Right" workshop because I'm interested in the topic. However the requirements are a bit of an issue for me and I think it's best if you have these mentioned in the workshop descriptions in the future.

I have a Mac and I'm not familiar with Microsoft's tech stack. I would have most likely chosen a different workshop if this information was presented from the start.

Thank you.

**Comment by sizovs** [comment]
Hey! Folks, if setting up Windows 10 / VS Studio is a showstopper, please DM Janis in Slack – let's see what we can do. 💡

**Comment by dmitryakadiamond** [comment]
Just want to +1 regarding windows problem, will email to Janis.

**Comment by mpavel** [comment]
@sizovs, the most likely idea (as far as I've seen so far) is to actually pair with someone during the Workshop. This sounds very reasonable to me and it shouldn't be an issue. Thank you.

**Comment by sizovs** [comment]
Another recommendation: it might be a good idea to make the workshop OS independent, by using .NET Core and Docker. Then more people could join and enjoy it 👌

**Comment by mpavel** [comment]
@sizovs I actually ended up looking thru the requirements a couple of times searching for exactly this 😄 I was hoping I missed the references haha

**Comment by DavidBoike** [comment]
@mpavel Where are you taking this workshop and from whom?

**Comment by DavidBoike** [comment]
Aha, I figured out from @sizovs's bio that you must be taking it from @jbogard at DevTernity.

I'll let Jimmy know. (Or rather, by pinging him I just did.)

We commonly call this workshop "SOA Done Right (with examples in ASP.NET and NServiceBus)" which usually communicates the tech stack pretty well, but I see that for whatever reason the only clue here was the tag (is it a tag?) `.net examples` which doesn't quite convey the same thing. Sorry about that!

**Comment by mpavel** [comment]
@DavidBoike, that's correct, I'll be attending the workshop at DevTernity in a few days. I was already in touch with the team there and there's a few more people in this situation (Mac, no Windows and not using the tech stack) and I will pair with someone for the day - this should work out well.

I will close the issue now. All the best!

**Comment by andrew-jung** [comment]
I managed to setup a vm on my Mac with Windows 10 and get the pre-reqs setup. It's pretty sluggish due to my hardware but may be possible if you have a better Mac than I!

Also would like to pair up as well just in case my Mac doesn't hold up to speed. :)
